apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tbaovpppe-go 
  janus-idp.io/tekton: tbaovpppe-go
  backstage.io/kubernetes-id: tbaovpppe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tbaovpppe-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  