apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tbaovpppe-go-gitops
  description: This is GitOps manifest for tbaovpppe-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: tbaovpppe-go
    backstage.io/kubernetes-id: tbaovpppe-go 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhopp-rhtap-testing/tbaovpppe-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tbaovpppe-go
